# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "63f434d84ede5f7dffe15ae1e4b0db6b"
application_url = "https://product-price-updater.onrender.com"
embedded = true
name = "Product-price-Updater"
handle = "product-price-updater-2"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://product-price-updater.onrender.com/auth/callback",
  "https://product-price-updater.onrender.com/auth/shopify/callback",
  "https://product-price-updater.onrender.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "earnestminds.myshopify.com"
automatically_update_urls_on_dev = true
