# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8eafc29cde766315fd81aeda3dd81998"
application_url = "https://heading-fell-aids-cl.trycloudflare.com"
embedded = true
name = "Gold Jwellery Price Editor"
handle = "gold-jwellery-price-editor-1"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://heading-fell-aids-cl.trycloudflare.com/auth/callback",
  "https://heading-fell-aids-cl.trycloudflare.com/auth/shopify/callback",
  "https://heading-fell-aids-cl.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "baubies.myshopify.com"
automatically_update_urls_on_dev = true
